[programs.localnet]
solana_raspberry_pi_test = "A26MswuiAAvKvqX2i8sDf1YPBT6cRwDPyLvm7P5rgaD4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "http://10.3.141.135:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy ="scp ./target/deploy/* ubuntu@10.3.141.135:~ && ssh ubuntu@10.3.141.135 ./solana-1.9.2/bin/solana program deploy --program-id ./solana_raspberry_pi_test-keypair.json ./solana_raspberry_pi_test.so"
